artifacts_root : artifacts

data_ingestion:
  root_dir : artifacts/data_ingestion
  source_path : D:/Deep_Learning_Projects/Sports_Classification/notebooks/data.zip
  local_data_file : artifacts/data_ingestion/data.zip
  unzip_dir : artifacts/data_ingestion