artifacts_root : D:/Deep_Learning_Projects/Sports_Classification/artifacts

data_ingestion:
  root_dir : D:/Deep_Learning_Projects/Sports_Classification/artifacts/data_ingestion
  source_path : D:/Deep_Learning_Projects/Sports_Classification/notebooks/data.zip
  local_data_file : D:/Deep_Learning_Projects/Sports_Classification/artifacts/data_ingestion/data/data.zip
  unzip_dir : D:/Deep_Learning_Projects/Sports_Classification/artifacts/data_ingestion/data/train/


base_model:
  root_dir : D:/Deep_Learning_Projects/Sports_Classification/artifacts/base_model
  base_model_path : D:/Deep_Learning_Projects/Sports_Classification/artifacts/base_model/base_model.h5
  updated_base_model_path : D:/Deep_Learning_Projects/Sports_Classification/artifacts/base_model/updated_base_model.h5


training:
  root_dir : D:/Deep_Learning_Projects/Sports_Classification/artifacts/model_training
  trained_model_path : D:/Deep_Learning_Projects/Sports_Classification/artifacts/model_training/model.h5